# Generated by Django 3.1.8 on 2023-01-07 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Usuario',
        ),
    ]
